version: '3.8'

services:
  db_postgres:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    networks:
      - app-network

  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - app-network

  user-aggregator:
    build: .
    container_name: user-aggregator
    restart: always
    depends_on:
      - db_postgres
      - db_mysql
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge