spring:
  application:
    name: user-aggregator
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/migration/{vendor}
    validate-on-migrate: true

aggregator:
  data-sources:
    - name: data-base-1
      strategy: postgres
      url: ${POSTGRES_URL}
      table: users
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name

    - name: data-base-2
      strategy: mysql
      url: ${MYSQL_URL}
      table: user_table
      user: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      mapping:
        id: ldap_id
        username: ldap_login
        name: name
        surname: surname